[package]
name = "rocketcamel/cameldebris"
description = "A very simple alternative to debris service that uses promises to schedule deletion of an instance after a certain amount of time."
version = "1.0.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
authors = ["rocketcamel"]

[dependencies]
promise = "evaera/promise@4.0.0"